name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup npm
        uses: npm/action-setup@v4

      - name: Install dependencies
        run: npm install

      - name: Generate environment variables
        run: find . -name ".env.local.example" -exec sh -c 'cp "$1" "${1%.example}"' _ {} \;

      - name: Typecheck
        run: npm typecheck

      - name: Lint
        run: npm lint