name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18 # or your required version

      - name: Install dependencies
        run: npm install

      - name: Generate environment variables
        run: find . -name ".env.local.example" -exec sh -c 'cp "$1" "${1%.example}"' _ {} \;

      - name: Typecheck
        run: npm run typecheck

      - name: Lint
        run: npm run lint
